version: '3'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"